logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
#      defaultZone: http://registry:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
#      user-info-uri: http://auth-service:5000/uaa/users/current
      user-info-uri: http://localhost:5000/uaa/users/current

spring:
  rabbitmq:
#    host: rabbitmq
    host: localhost
    port: 5673

management:
  web:
    exposure:
      include: "*"