spring:
  data:
    mongodb:
#      host: auth-mongodb
      host: localhost
      username: user
      password: ${MONGODB_PASSWORD:password}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
