spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD:password}

# read config from github
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/path to repo
#          search-paths: config-repo

server:
  port: 8888

